services:
    pg:
        image: postgres:15
        container_name: ssw_pg
        restart: unless-stopped
        environment:
            POSTGRES_DB: ssw_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
        ports:
            - "54329:5432"

    pgadmin:
        image: dpage/pgadmin4
        container_name: ssw_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - "5050:80"
        depends_on:
            - pg

    typesense:
        container_name: typesense
        image: 'typesense/typesense:26.0'
        ports:
            - '${FORWARD_TYPESENSE_PORT:-8108}:8108'
        environment:
            TYPESENSE_DATA_DIR: '${TYPESENSE_DATA_DIR:-/typesense-data}'
            TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'
            TYPESENSE_ENABLE_CORS: '${TYPESENSE_ENABLE_CORS:-true}'
        volumes:
            - 'typesense_data:/typesense-data'
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:8108/health'
            retries: 5
            timeout: 7s
volumes:
    typesense_data:
        driver: local
    postgres_data:
