services:
    pg:
        image: postgres:15
        container_name: SPLIT-POSTGRES
        restart: unless-stopped
        environment:
            POSTGRES_DB: split_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
        ports:
            - "54329:5432"

    pgadmin:
        image: dpage/pgadmin4
        container_name: SPLIT-PGADMIN
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - "5050:80"
        depends_on:
            - pg
volumes:
    postgres_data:
